# Generated by Django 6.1.1 on 2026-09-17 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFitnessEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('food_intake', models.PositiveIntegerField(blank=True, null=True)),
                ('steps', models.PositiveIntegerField(blank=True, null=True)),
                ('water_intake', models.FloatField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('exercise', models.CharField(blank=True, choices=[('Running', 'Running'), ('Walking', 'Walking'), ('Cycling', 'Cycling'), ('Squats', 'Squats'), ('Lunges', 'Lunges'), ('Push-ups', 'Push-ups'), ('Pull-ups', 'Pull-ups'), ('Bench Press', 'Bench Press'), ('Lat Pulldown', 'Lat Pulldown'), ('Plank', 'Plank'), ('Yoga', 'Yoga'), ('Swimming', 'Swimming'), ('Other', 'Other')], max_length=100)),
                ('custom_exercise', models.CharField(blank=True, max_length=100)),
                ('workout_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('fitness_goal', models.CharField(blank=True, choices=[('Lose Weight', 'Lose Weight'), ('Gain Weight', 'Gain Weight'), ('Maintain Weight', 'Maintain Weight'), ('Build Muscle', 'Build Muscle'), ('Improve Fitness', 'Improve Fitness'), ('Increase Strength', 'Increase Strength'), ('Improve Endurance', 'Improve Endurance'), ('General Health', 'General Health')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_entry')],
            },
        ),
    ]
