# Generated by Django 6.1.1 on 2026-09-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyfitnessentry',
            name='custom_exercise',
        ),
        migrations.RemoveField(
            model_name='dailyfitnessentry',
            name='exercise',
        ),
        migrations.AddField(
            model_name='dailyfitnessentry',
            name='exercises',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
